Razor v2
razor-network/datasources pull request #87
Opened 2024-09-19 06:37 UTC by yohanelly95

---
name: Refresh inactive jobs for V2 and Staging parity

---

## Description
Updated the current active collection jobs list, removing unused and inactive jobs. Staging updated to have parity with mainnet.

## Type of change

Please mark the options that apply to this PR.

- [ ] New job
- [ ] New collection
- [ ] API is valid, example API response: 
- [ ] This change requires a documentation update

## Checklist:

- [ ] I have performed a self-review of my own code and it conforms with the formatting
- [ ] I have added tests that prove my Job/Collection is valid and all tests are passing
- [ ] I have made corresponding changes to the documentation

2024-09-23 05:25 UTC, rajkharvar approved these changes

2024-09-25 09:28 UTC, Yashk767 requested changes

2024-09-25 09:28 UTC, Yashk767 commented on mainnet/jobs.json
> +      "selector": "[USD]",
The selector here should be `USD` instead of `[USD]` for `cryptocompare` API's, our current schain mainnet has this change @yohanelly95

2024-09-25 09:28 UTC, Yashk767 commented on mainnet/jobs.json
> +      "selector": "[USD]",
Here as well, the selector should be `USD` instead of `[USD]` for cryptocompare API's.

2024-09-25 09:39 UTC, Yashk767 approved these changes

2024-09-25 09:42 UTC, rajkharvar approved these changes

2024-09-25 11:01 UTC, merged